### ISSUE TITLE
Installation failed on Mac 

### ISSUE THREAD

**Issue by cyx96** [scikit-tda/ripser.py#102]
Hi, my installation of ripser on Mac failed with the following error:

Running setup.py clean for ripser
Failed to build ripser
DEPRECATION: Could not build wheels for ripser which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: umap-learn, ripser, tadasets, scikit-tda
    Running setup.py install for ripser ... error

I tried updating Xcode command line tool as the other issues suggested, but it didn’t work for me. I think this might have something to do with https://github.com/pypa/pip/issues/8368?

**Comment by cyx96** [comment]
I just found that using conda-forge to install ripser works for me. Maybe I should put the link here: https://github.com/conda-forge/ripser-feedstock for people having trouble installing ripser with pip.

**Comment by sauln** [comment]
I'm glad the conda-forge worked for you. I'm surprised the build failed though. I'll try figuring out what the problem is.
