### ISSUE TITLE
Incorrect output on COO matrices instantiated with rows and columns not in lexicographic order

### ISSUE THREAD

**Issue by ulupo** [scikit-tda/ripser.py#103]
I'm observing inconsistent behaviour between different `scipy` sparse formats which suggests to me that `ripser` is secretly assuming that matrices in COO format have lexicographically ordered `row` and `column` arrays. I believe that, when calling `tocoo()` on a non-COO matrix as is done internally by `ripser`, `scipy` automatically performs lexicographic ordering.  But of course, on COO input, `tocoo()` does nothing at all.  Hence, it seems to me that incorrect results are computed on certain valid-looking COO input.

Here's an example:
```
from ripser import ripser
import numpy as np
from scipy.sparse import coo_matrix

data = np.array([6., 8., 2., 4., 5., 9., 10., 3., 1., 1.])
row = np.array([0, 0, 0, 0, 1, 1, 1, 2, 2, 3])
col = np.array([4, 1, 3, 2, 4, 3, 2, 3, 4, 4])
dm = coo_matrix((data, (row, col)), shape=(5, 5))
```
`dm` is an upper-triangular matrix (more on symmetric matrices below), and its array representation looks like this:
```
array([[ 0.,  8.,  4.,  2.,  6.],
       [ 0.,  0., 10.,  9.,  5.],
       [ 0.,  0.,  0.,  3.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.]])
```
Now,
```
ripser(dm, distance_matrix=True)['dgms']
```
returns
```
[array([[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  2.],
        [ 0.,  5.],
        [ 0., inf]]),
 array([[ 8., inf],
        [ 4., inf]])]
```
Notice the two infinite bars in 1D. Contrast this with the output of:
```
ripser(dm.tocsr(), distance_matrix=True)['dgms']
```
which is
```
[array([[ 0.,  1.],
        [ 0.,  1.],
        [ 0.,  2.],
        [ 0.,  5.],
        [ 0., inf]]),
 array([], shape=(0, 2), dtype=float64)]
```
with no infinite bars in 1D, and looking correct (e.g. equal to the result of running on `dm.toarray()`). This is also the output of `ripser(dm.tocsr().tocoo(), distance_matrix=True)['dgms']`, I believe because the double-conversion performs lexicographic ordering of the row and column index pairs.

As an aside, I want to reassure that this does not seem to have to do with the fact that the input is only upper-triangular. Try symmetrizing as follows:
```
data_symm = np.hstack([data, data])
row_symm = np.hstack([row, col])
col_symm = np.hstack([col, row])
dm_symm = coo_matrix((data_symm, (row_symm, col_symm)))
```
Then `ripser(dm_symm , distance_matrix=True)['dgms']` yields the same incorrect result.

**Comment by ulupo** [comment]
I have a 2-line fix that I'm happy to submit via a PR.

**Comment by ctralie** [comment]
Good catch. Yes please on the PR! Thank you so much

**Comment by ctralie** [comment]
Thank you again for your contribution @ulupo!  I added the unit test and pushed a new version to pypi
