### ISSUE TITLE
Docs out of date?

### ISSUE THREAD

**Issue by bdice** [scikit-tda/ripser.py#107]
Just wanted to check, is https://ripser.scikit-tda.org/ the right URL for the docs? It says in the title that the docs are for ripser 0.3.2. It looks like the latest package version is 0.5.4. I was showing this tool to some colleagues and just wanted to be sure I had the latest and greatest docs. 😉

**Comment by sauln** [comment]
Yup, thanks for pointing this out!  I'll dig up the doc deployment instructions and see if we can't move over to readthedocs or something where it'll be automated.

**Comment by ctralie** [comment]
Thank you Bradley for pointing this out and Nathaniel for helping to
automate it!  I've been so swamped with remote teaching I wasn't able to
respond and do this manually

**Comment by bdice** [comment]
@sauln @ctralie Feel free to ping me if you need help, I have done a few ReadTheDocs deployments before. 😄

**Comment by catanzaromj** [comment]
The docs now correctly build and deploy with updated recipes from https://github.com/scikit-tda/ripser.py/pull/157
