### ISSUE TITLE
Rips for 1d data

### ISSUE THREAD

**Issue by xchhuang** [scikit-tda/ripser.py#111]
Hi,

I would like to ask what the persistence diagram should look like for 1D data. I tested with the following code:
```
import numpy as np
from ripser import ripser
from persim import plot_diagrams
import matplotlib.pyplot as plt

data = np.random.random((100,1))
plt.plot(data)
plt.show()
diagrams = ripser(data)['dgms']
print (type(diagrams), diagrams)
plot_diagrams(diagrams, show=True)
```

The data and its PD is shown in the following:
<img src="https://user-images.githubusercontent.com/22114321/97057006-99817380-158a-11eb-9a30-3859d1565cc4.png" width="30%" height="30%"><img src="https://user-images.githubusercontent.com/22114321/97057225-101e7100-158b-11eb-9298-8c9cd8287f8a.png" width="30%" height="30%">

Here `H1` is empty. However, in this video https://www.youtube.com/watch?v=AWoeBzJd7uQ&t=265s (at 14 min.), there should be points on `H1`. So I wonder what's wrong with my code. Thanks in advance.

**Comment by sauln** [comment]
Hey! To get the h1, you'll have to apply ripser to the Takens embedding of the time series, not just the time series.  You can take a sliding window of say 10 observations.  That would give you a 10 dimensional space you can apply ripser to.  Then you should start seeing h1 pop up.

**Comment by xchhuang** [comment]
@sauln Good to know, thanks for your answer!
