### ISSUE TITLE
Cocycles with sparse matrices

### ISSUE THREAD

**Issue by dcarmod2** [scikit-tda/ripser.py#117]
First, thank you for your work on this package! 

In ripser.py, the call to DRFDMSparse doesn't pass do_cocycles, meaning do_cocycles is always set to the default value of zero when the input to ripser is a sparse matrix. 

I'm not sure if this was on purpose, but some small test cases seem to work fine when editing the .py file to pass the user supplied do_cocycles through.

**Comment by ctralie** [comment]
Ah, great catch!  Would you mind submitting a pull request?

**Comment by dcarmod2** [comment]
Sure thing, submitted one

**Comment by ctralie** [comment]
Thank you again for this, this was a good catch!
