### ISSUE TITLE
std::overflow_error

### ISSUE THREAD

**Issue by IbtihalFerwana** [scikit-tda/ripser.py#124]
Hello, 
I'm using ripser with distance matrix, what could be the reason I'm facing the following error?
`terminate called after throwing an instance of 'std::overflow_error'
  what():  simplex index 36030876301887160 in filtration is larger than maximum index 36028797018963967`

**Comment by catanzaromj** [comment]
This is an overflow error--you're computing ripser on too large of a dataset. This might be addressed in future versions of the upstream ripser, but for now, there's nothing we can do about this. Try subsampling your dataset or put an upper threshold on the radii of balls you use (`thresh` parameter in `ripser.ripser` and `ripser.Rips`)
