### ISSUE TITLE
Issue with plotting dependencies import

### ISSUE THREAD

**Issue by ghilesmeddour** [scikit-tda/ripser.py#125]
Hi,

`matplotlib` an `persim` imports are causing me trouble (in a context where I have no need for plotting). Would you please consider making those imports lazy?

**Comment by ghilesmeddour** [comment]
I made a [PR for this](https://github.com/scikit-tda/ripser.py/pull/126)

**Comment by sauln** [comment]
Sure. Let's give it a try.

**Comment by sauln** [comment]
@ghilesmeddour ,  I forgot to ask, could you bump the patch version in `ripser/_version.py`. Then I'll cut a new release so you can install directly from pypi.  It'll have to be a second PR since I merged this one before remembering 🤦

**Comment by ghilesmeddour** [comment]
@sauln thanks for your reactivity <3, [PR here](https://github.com/scikit-tda/ripser.py/pull/127)

**Comment by sauln** [comment]
Rad.  A release has been cut. It should be available on pypi in a few minutes.  

Thanks for your contribution!

**Comment by ctralie** [comment]
Thanks all!

**Comment by ghilesmeddour** [comment]
This solved my problem. Thank you all!
