### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by Audrique** [scikit-tda/ripser.py#149]
I used ripser last year and it worked. Today, I wanted to use ripser again, however, it gave me the above error. I tried upgrading/reinstalling both ripser and numpy. Doing so gave me the error:
"ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.6.0 requires daal==2021.4.0, which is not installed.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.24.2 which is incompatible."

I guess this means that ripser needs numpy 1.18 and is not compatible with numpy 1.24.2 yet?

**Comment by catanzaromj** [comment]
It appears that your current environment has `numpy == 1.24.2` but `numba 0.55.1 requires numpy < 1.22`. You can try downgrading your version of numpy with something like `pip install --force-reinstall -v "numpy<1.22"`. I would also recommend using dedicated environments for projects with conda or virtualenv in case you're not already doing so.
