### ISSUE TITLE
Missing wheels for 0.6.5

### ISSUE THREAD

**Issue by jonyscathe** [scikit-tda/ripser.py#155]
0.6.5 release on PyPI only has one file: ripser-0.6.5-cp39-cp39-win_amd64.whl 
No wheels for Linux, no source distribution.

**Comment by ctralie** [comment]
Wow, that is disturbing, thank you for bringing this to my attention!  I will fix it as soon as I can.

For now, you can clone the ripser.py repository and type the following from within the root of the repository:

```
pip install -e .
```

**Comment by ctralie** [comment]
Hello @jonyscathe 
I believe @catanzaromj fixed this in the most recent release, 0.6.7.  Please verify that all of the files are there that you need, and I can close this issue.  Thank you again for bringing this to our attention!

**Comment by jonyscathe** [comment]
Hi @ctralie,

Yep, I can install 0.6.7 on an Ubuntu machine.
There are still no Linux wheels, but it builds from source distribution just fine so that is good enough for me.

**Comment by catanzaromj** [comment]
@jonyscathe Sorry about this. I just realized that only windows distros have wheels--the linux wheels are still failing. I'll fix this shortly.

**Comment by jonyscathe** [comment]
Hi @catanzaromj, not really an issue for me as 0.6.7 is installing on Linux from the source distribution fine.
But I guess it is worth fixing if it is a simple fix.
