### ISSUE TITLE
Compile ripser with numpy 2.x

### ISSUE THREAD

**Issue by jonyscathe** [scikit-tda/ripser.py#165]
With python 3.12.4 with numpy==2.0.0 and ripser==0.6.8 the following code:
```
from ripser import ripser
```
Leads to the following ImportError:
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/home/.../.cache/pypoetry/virtualenvs/.../lib/python3.12/site-packages/ripser/__init__.py", line 1, in <module>
    from .ripser import *
  File "/home/.../.cache/pypoetry/virtualenvs/.../lib/python3.12/site-packages/ripser/ripser.py", line 34, in <module>
    from pyRipser import doRipsFiltrationDM as DRFDM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../.cache/pypoetry/virtualenvs/.../lib/python3.12/site-packages/ripser/__init__.py", line 1, in <module>
    from .ripser import *
  File "/home/.../.cache/pypoetry/virtualenvs/.../lib/python3.12/site-packages/ripser/ripser.py", line 34, in <module>
    from pyRipser import doRipsFiltrationDM as DRFDM
  File "ripser/pyRipser.pyx", line 1, in init pyRipser
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

**Comment by EveWCheng** [comment]
If you downgrade numpy to the previous version it works just fine.

**Comment by jonyscathe** [comment]
@EveWCheng I understand that.
I opened this issue with the hope that ripser could support both numpy 1.x and numpy 2.x at some point. I would have thought that would be desirable for a lot of ripser uses.

**Comment by ctralie** [comment]
Thank you @EveWCheng for that information, and thank you @jonyscathe for bringing this to our attention.  Looks like I need to make a new release with numpy 2.0 support.  Hopefully it will be straightforward, but you never know with these things.  I'll try as soon as I can

**Comment by catanzaromj** [comment]
@ctralie I think I need to clean up the release process first. I found a bug in it with the last release I made of persim. I'll try to fix that within the next week, and then propagate it to the scikit-tda packages.

**Comment by ctralie** [comment]
Thank you so much @catanzaromj!  Let me know what you think the next steps should be here, and if we should go ahead and update the build
