### ISSUE TITLE
Add osx-arm64 (or noarch) build to conda-forge distribution

### ISSUE THREAD

**Issue by smcolby** [scikit-tda/ripser.py#182]
Currently ripser builds for win-64, osx-64, and linux-64 platforms on anaconda. Missing, however, is a build for osx-arm64, i.e. for macs with Apple silicon (M* chips). 

Installation via PyPI is viable, but I am trying to build a conda package with ripser as a dependency; lack of osx-arm64 (or a noarch build) prohibits inclusion of ripser in conda recipes intended for cross-platform distribution.

**Comment by catanzaromj** [comment]
Thanks @smcolby. I created a [PR](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6861) for this so we'll see what happens.

**Comment by catanzaromj** [comment]
https://github.com/conda-forge/ripser-feedstock/pull/31

**Comment by catanzaromj** [comment]
@smcolby I believe we got everything merged in and now osx-arm64 builds are available for ripser on conda-forge. See here https://anaconda.org/conda-forge/ripser

Can you try installing on a mac and verify?

**Comment by smcolby** [comment]
Working perfectly, thank you!
