### ISSUE TITLE
Write up Moebius Notebook

### ISSUE THREAD

**Issue by ctralie** [scikit-tda/ripser.py#4]
To demonstrate the capability of changing the field of coefficients

**Comment by sauln** [comment]
I converted the old Moebius example into Python:
https://github.com/ctralie/ripser/blob/master/examples/moebius_strip.py

Is this what you envisioned?

**Comment by ctralie** [comment]
Yup, exactly.  This is an example of where you see something interesting
with different fields.  With Z/2, you see a class die and a class form when
the strip width is filled in.  But for Z/3, there is only ever one class;
the strip boundary doesn't bound when the strip width is filled in
