### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Hancya** [scikit-tda/ripser.py#52]
Hello,

I want to use Ripser for my independent study, but I'm unable to install it. I first tried to install it via PyPy, but with command "pip install ripser" I get the error message

```
Command "c:\users\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\AppData\\Local\\Temp\\pip-install-8xwi42nr\\ripser\\setup.py';
f=getattr(tokenize, 'open', open)(__file__);
code=f.read().replace('\r\n', '\n');
f.close();
exec(compile(code, __file__, 'exec'))" 
install --record C:\Users\AppData\Local\Temp\pip-record-bmouiamb\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\AppData\Local\Temp\pip-install-8xwi42nr\ripser\
```
Then I tried to download the whole package from GitHub and after I located the folder where the package is downloaded, with command "python setup.py", I get the error message "
```
274: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

What should I do? Please let me know. Thank you!

>

**Comment by sauln** [comment]
Hi, thanks for reaching out.  

First, I tried reformatting your issue with code formatting using "```" so it renders correctly.  Does that look right?

When you install from source, you need to give `setup.py` a command `install`.

Try installing with the command:
```
python setup.py install
```

**Comment by Hancya** [comment]
I just tried the command, but here is the new error message:

error: command 'cl.exe' failed: No such file or directory

**Comment by Hancya** [comment]
The context of the error message:

> 

> building 'pyRipser' extension
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -DUSE_COEFFICIENTS=1 -DNDEBUG=1 -DASSEMBLE_REDUCTION_MATRIX=1 -I.\ripser -IC:\Users\shelv\AppData\Local\Programs\Python\Python37-32\include -IC:\Users\shelv\AppData\Local\Programs\Python\Python37-32\include -IC:\Users\shelv\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /EHsc /Tpripser/pyRipser.cpp /Fobuild\temp.win32-3.7\Release\ripser/pyRipser.obj -v -std=c++11 -Ofast -D_hypot=hypot
error: command 'cl.exe' failed: No such file or directory"

**Comment by ctralie** [comment]
Hello,
See if you are able to install the mingw runtimes:

https://sourceforge.net/projects/mingw-w64/

and then try pip
