### ISSUE TITLE
Handle multiplicity of points in visualization

### ISSUE THREAD

**Issue by sauln** [scikit-tda/ripser.py#54]
Currently, the visualization does not indicate whether there are points being overplotted. 

We could possibly:
- Add jitter (this could be confusing as it would change the interpretation of the diagrams).
- Make points opaque so multiple points are easy to see.
- Add annotations indicating multiplicity.

**Comment by ctralie** [comment]
Yes this issue came up during the Italy workshop actually.  My vote would
be annotations for multiplicity greater than 1 if it happens.  Also,
perhaps we should create an alternative plot for persistence bars also,
where this issue doesn't occur

**Comment by sauln** [comment]
I would also like annotations, but I think they could easily become overcrowded. 

As a quick solution, I make some changes to the defaults so they are slightly opaque and have a border. This makes it a little easier to see multiplicity.

**Comment by sauln** [comment]
Plotting has been moved to https://github.com/scikit-tda/persim
