### ISSUE TITLE
Advice 

### ISSUE THREAD

**Issue by fmayah** [scikit-tda/ripser.py#57]
Hi 

I am trying to use ripser but I can't go forward unfortunately.
The following two steps 
pip install Cython
pip install Ripser
work without any problem.
But this is not work
>>> import numpy as np
>>> from ripser import ripser, plot_dgms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/admin/ripser.py", line 1
    /*
    ^
SyntaxError: invalid syntax

Please, advise me to fix the problem.
Regards

Faik Mayah

**Comment by sauln** [comment]
Is the script that named ‘ripser.py’?  If so, then python will get confused when you try loading the library, and instead load the script.  

Try naming it something different.
