### ISSUE TITLE
Unable to import Ripster

### ISSUE THREAD

**Issue by YannRoussel** [scikit-tda/ripser.py#70]
Hi,

I could install Ripster succesfully but when I am trying to import it I get the error:

.../lib/python3.7/site-packages/Cython/Includes/numpy/__init__.pxd in init pyRipser()

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

Apparently it is happening when compiling these lines from ripser.py:
---> 38 from pyRipser import doRipsFiltrationDM as DRFDM
and/or
---> 39 from pyRipser import doRipsFiltrationDMSparse as DRFDMSparse

I don't know how I could fix this, any help is welcome (Cython is up to date).

Thank you.

**Comment by sauln** [comment]
What operating system do you use?

**Comment by YannRoussel** [comment]
I am on MacOS 10.14.3 (Mojave)

**Comment by sauln** [comment]
Have you tried updating your Xcode command line tools?

**Comment by YannRoussel** [comment]
Yes but I still get the same error.

**Comment by evnrse** [comment]
have same error on WIndows 10

**Comment by evnrse** [comment]
I dont know why, but it work for me
1. conda create -n test_env python=3.6.3 anaconda
2. Download ripser-0.3.2-cp36-cp36m-win_amd64.whl whl from https://pypi.org/project/ripser/#files 
3. pip install --ignore-installed  ripser-0.3.2-cp36-cp36m-win_amd64.whl

**Comment by sauln** [comment]
Everything should be good to go with Ripser.py 0.4.1 💯
