### ISSUE TITLE
do you have video how to use it?

### ISSUE THREAD

**Issue by Sandy4321** [scikit-tda/ripser.py#71]
do you have video how to use it?

**Comment by sauln** [comment]
Sorry no, no videos. 

Is there something about videos that the written documentation would be insufficient for?

**Comment by Sandy4321** [comment]
I see
then maybe short code to understand main ideas?

**Comment by sauln** [comment]
Have you tried looking at [ripser.scikit-tda.org](https://ripser.scikit-tda.org)?

**Comment by Sandy4321** [comment]
yes , it is not clear what is it 
Is it new kind if t-SNE
seems to be it is something interesting, but what is it?

**Comment by sauln** [comment]
[This paper](https://www.math.upenn.edu/~ghrist/preprints/barcodes.pdf) is a great introduction to the general idea of persistent homology.

**Comment by Sandy4321** [comment]
looks good bu titi s too long for main idea description, so it  is not something similar to t-SNE

**Comment by ctralie** [comment]
Have a look here:
http://www.ctralie.com/Research/SlidingWindowVideo-SOCG2016/background.html#tda

**Comment by Sandy4321** [comment]
looks interesting thank, but on practice is it better than t-SNE or algorithms based on graphs
how this can help with standard AI problems like classification or visualization for multidimensional data?
