### ISSUE TITLE
Key Error in Representative Cocycles tutorial

### ISSUE THREAD

**Issue by Mahdisadjadi** [scikit-tda/ripser.py#74]
In `Representative Cocycles` tutorial, this code block

```
result = ripser(x, coeff=17, do_cocycles=True)
diagrams = result['dgms']
cocycles = result['cocycles']
D = result['dm']
```

raises a `KeyError: 'dm'` since returned object doesn't have the key. The available keys are:

```
result.keys()
# ['dgms', 'cocycles', 'num_edges', 'dperm2all', 'idx_perm', 'r_cover']
```

**Comment by ctralie** [comment]
Thanks for the heads up!  The API has changed, so 'dm' is in fact 'dperm2all' now.  @sauln I am having a hard time installing the updated version of ripser.py on my machine, do you think you could verify that works?

**Comment by lingzhou0** [comment]
> Thanks for the heads up! The API has changed, so 'dm' is in fact 'dperm2all' now. @sauln I am having a hard time installing the updated version of ripser.py on my machine, do you think you could verify that works?

It works for me. Thanks for the update!
