### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by tmelorc** [scikit-tda/ripser.py#75]
I'm using Python 2.7 on Linux and the minimal given example does not work. 
I have upgraded `cython` and have installed `persim` via `pip` but I got the following error:

```
    diagrams = ripser(data)['dgms']
TypeError: 'module' object is not callable
```

Any idea?

**Comment by sauln** [comment]
Which example is this?

It looks like you are importing the ripser module and calling it, like
```
import ripser
diagrams = ripser(data)['dgms']
```

You should instead do

```
from ripser import ripser
diagrams = ripser(data)['dgms']
```

as there is a function called `ripser` that does the computation. This is a little confusing having them both named the same thing. We're open to suggestions for API changes.

**Comment by tmelorc** [comment]
I'm trying this example, from Usage section.
```
import numpy as np
from ripser import ripser
from persim import plot_diagrams

data = np.random.random((100,2))
diagrams = ripser(data)['dgms']
plot_diagrams(diagrams)
```

Now, no errors anymore, but nothing happens. No plots are shown. 
I think diagrams were created since printing it I see an array. The problem is with `plot_diagrams()` function. 

Any idea? Regards.

**Comment by sauln** [comment]
If you're not in a notebook, you'll need to tell matplotlib to show the plot:

```
plot_diagrams(diagrams, show=True)
```

I'll update the docs to reflect this.

**Comment by sauln** [comment]
If this doesn't work, it might be a problem with 2.7 that we haven't accounted for. If so, please reopen the issue and we can figure out what's going on.

**Comment by tmelorc** [comment]
Thanks so much. Now it makes sense and it works as in the following:
```
import matplotlib.pyplot as plt
import numpy as np
from ripser import ripser, Rips
from persim import plot_diagrams

data = np.random.random((100,2))
diagrams = ripser(data)['dgms']
plot_diagrams(diagrams)
plt.show()
```
The complete example above could be useful in documentation. 
Thanks.
