### ISSUE TITLE
Unable to import ripser

### ISSUE THREAD

**Issue by aggmanu** [scikit-tda/ripser.py#77]
Hi,
I get the following error when importing ripser:

ImportError: /home/......../.local/lib/python3.7/site-packages/pyRipser.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNSt8ios_base4InitD1Ev

I am on CentOS 7.

**Comment by sauln** [comment]
Everything should be good to go with Ripser.py 0.4.1 💯
