### ISSUE TITLE
Documentation for ripser suggestions

### ISSUE THREAD

**Issue by milkpowder101** [scikit-tda/ripser.py#79]
Docs in https://ripser.scikit-tda.org/ is a mirror of https://github.com/scikit-tda/ripser.py/blob/master/docs/index.rst

```For the original C++ library, see Ripser/ripser.``` 
The link should update to source code instead of release tag, currently it's showing release tag.

in `Example Usage` , ```r.plot(diagram, show=True)``` is not show any plot.

**Comment by sauln** [comment]
Thanks for the suggestions! I merged the changes in PR #80.
