### ISSUE TITLE
Using Z/17 in Representative Cocycles tutorial

### ISSUE THREAD

**Issue by CodyArmond** [scikit-tda/ripser.py#83]
Hello, I am working on expanding the explanation of cohomology in this tutorial, but I had a question about the following statement:

> The death edge between 3_8 has been removed. For the remaining triangles, we can now verify that the cocycle condition is satisfied. **For instance, for triangle 0_2_11, we have 1 + 16 + 0 = 17 = 0 (mod 17).** Along triangle 0_1_2 we have 0 + 1 - 1 (since the edge 2_0 is negatively oriented), which is 0 (mod 17).

The problem is that the edge 2_11 is above the threshold and not part of the simplicial complex. As it stands all edges evaluate to either 1 or 0. Has the example changed since this was written?

**Comment by ctralie** [comment]
Hello,
Thank you for pointing this out, and my sincerest apologies for the delay in my response.  You are absolutely right.  Something got lost in translation as we were moving notebooks and code around creating the larger scikit-tda project.  Please have a look at this new notebook and let me know if this example makes more sense:
https://github.com/scikit-tda/ripser.py/blob/fixingcocyclenotebook/docs/notebooks/Representative%20Cocycles.ipynb
Many thanks,
Chris

**Comment by catanzaromj** [comment]
@ctralie This never made it into the docs. Is there any reason why not? Should I add it in?
