### ISSUE TITLE
H_0 Connectedness

### ISSUE THREAD

**Issue by antht9** [scikit-tda/ripser.py#87]
Dear authors, 

Thank you for your wonderful library. It was easy-to-install and could be used right away! 

I have a question regarding detection in H_0. Suppose you had a data set living in, say, a 10 x 10 grid where the points are integer pairs (x, y). In addition, suppose there were two points (0, 0) and (1, 0). We would connect these points provided that d(x,y) <= 0.5. If we measure H_0, wouldn't that bar have a life time of 0.5 to some death? When I apply ripser(), I am obtaining a birth of 0 and death of 1. I am not sure why this is happening or if it is a fundamental error in interpretation on my end. 

If you could please provide any assistance or insight, I would greatly appreciate it. Thank you!

Kind regards,
Anthony

**Comment by ctralie** [comment]
Hi Anthony,
Thank you for using our library!

Hmm, that's strange.  As you describe it, indeed nothing should be
exceeding 0.5.  Would you mind uploading the exact distance matrix or image
you're using?  I can have a look.
Best,
Chris

**Comment by ubauer** [comment]
Hi,

in the underlying Ripser library, the Rips filtration is indexed by diameter, so the death at 1 is actually the intended behavior. This is a common convention in the literature, the other convention (half the diameter) is mostly used to obtain matching 1-skeleta for Cech and Rips complexes. As far as I can see, the values are not changed in the Python wrapper.

Best, Uli

**Comment by antht9** [comment]
Thank you for your fast reply, Chris and Uli! Yes, that makes sense now. I am used to indexing by radius, and had suspected this may be by diameter. I appreciate the clarification. 

For the future, would commenting with issues or direct e-mail be the best method of contact should I have some questions about the library? 

Thank you very much again for your time.

**Comment by ctralie** [comment]
Thanks for weighing in Uli!  I'm still not quite sure that this is the
issue if Anthony is setting up a distance matrix with 0.5 entries in it
(since we interpret entries in the distance matrix to be a diameter), but
it could be.  This is why I'd still like to check.

And yes, for me, this is the best way to ask questions, since answers I
provide can be useful to the whole community

**Comment by antht9** [comment]
Hi Chris, here is an image as you requested of the figure I am examining. 

![Figure_RipserGithub_Issue](https://user-images.githubusercontent.com/44580728/68252404-72d1d200-fff3-11e9-9910-7b031e098049.png)

Here, points have the form (i, j, 0), where i, j are positive integers. In rectangular coordinates, points are separated by distance 1. Diagonally, it is sqrt(2). Here is also the persistence diagram that comes with it. 

![1](https://user-images.githubusercontent.com/44580728/68252453-972dae80-fff3-11e9-857a-f7d6dc81b944.png)

Please let me know your thoughts.

**Comment by ctralie** [comment]
Oh, okay!  Uli is exactly right then.  I thought you were doing a lower
star filtration on an image, in which case there might have been a bug.
But for point clouds, we indeed use the diameter of balls (really the
distance between points) as the filtration values
