### ISSUE TITLE
Segmentation fault 11

### ISSUE THREAD

**Issue by tyler-foxworthy** [scikit-tda/ripser.py#89]
Thank you for putting together and maintaining this excellent library. It is wonderfully documented and up until now I've had no issues with it. 

I recently ran into an issue when calling ripser(dX,distance_matrix=True) in a loop for a dynamical systems analysis where the application crashes due to a segmentation fault 11 error. I'm admittedly not super knowledgable about diagnosing the root cause of this type of error, but I was not able to reproduce it just by replicating the same input (30x30) matrix. The error only pops up after long runs (e.g. greater than 200 iterations).

**Comment by bdice** [comment]
Debugging segfaults can be tough. Try running `import faulthandler; faulthandler.enable()` at the top of your script to get just a bit more info from segfaults. I am not a maintainer or expert on the C++ internals of this package but that may be helpful for identifying the problem.
